function fab = GetFABFromSectorIndex(idx, gsl_sector_names)
    % gsl_sector_names = cell array of sector names parsed from S; lines
    sector_name = gsl_sector_names{idx};  % +1 because MATLAB is 1-based
    prefix = sector_name(1:2);

    prefix_to_country = containers.Map( ...
        {'EB', 'ED', 'EE', 'EF', 'EG', 'EH', 'EI', 'EK', 'EL', ...
         'EN', 'EP', 'ES', 'ET', 'EV', 'EY', 'LF', 'LG', 'LH', ...
         'LI', 'LJ', 'LK', 'LL', 'LM', 'LN', 'LO', 'LP', 'LR', ...
         'LS', 'LT', 'LU', 'LV', 'LE', 'GC'}, ...
        {'Belgium', 'Germany', 'Estonia', 'Finland', 'United Kingdom', 'Netherlands', 'Ireland', ...
         'Denmark', 'Greece', 'Norway', 'Poland', 'Sweden', 'Germany', 'Latvia', 'Lithuania', ...
         'France', 'Greece', 'Hungary', 'Italy', 'Slovenia', 'Czech Republic', 'Israel', ...
         'Malta', 'Albania', 'Austria', 'Portugal', 'Romania', 'Switzerland', 'Turkey', ...
         'Moldova', 'Latvia', 'Spain', 'Spain'} ...
    );

    country_to_fab = containers.Map( ...
        {'United Kingdom','Ireland', ...
         'France','Germany','Netherlands','Belgium','Switzerland', ...
         'Italy','Greece','Cyprus','Malta', ...
         'Spain','Portugal', ...
         'Austria','Czech Republic','Slovenia','Croatia','Hungary','Slovakia', ...
         'Poland','Lithuania', ...
         'Sweden','Denmark', ...
         'Finland','Norway','Iceland','Estonia','Latvia', ...
         'Bulgaria','Romania'}, ...
        {'UK-IRE','UK-IRE', ...
         'FABEC','FABEC','FABEC','FABEC','FABEC', ...
         'BLUE-MED','BLUE-MED','BLUE-MED','BLUE-MED', ...
         'SW-FAB','SW-FAB', ...
         'FAB-CE','FAB-CE','FAB-CE','FAB-CE','FAB-CE','FAB-CE', ...
         'Baltic-FAB','Baltic-FAB', ...
         'DK-SE-FAB','DK-SE-FAB', ...
         'NE-FAB','NE-FAB','NE-FAB','NE-FAB','NE-FAB', ...
         'DANUBE-FAB','DANUBE-FAB'} ...
    );

    if isKey(prefix_to_country, prefix)
        country = prefix_to_country(prefix);
        if isKey(country_to_fab, country)
            fab = country_to_fab(country);
        else
            fab = 'Unknown-FAB';
        end
    else
        % country = "Unknown" + prefix;
        fab = 'Unknown-FAB';
    end
end
